import React from 'react';

export default function Question1(){
    return(
        <div className="question mt-40">
            <h4 className="h-4 h-bold">
                <span style={{opacity:"0.4", marginRight:"10px"}}>
                    01.
                </span>
                Definitions and Key Terms
            </h4>
            <p className="paragraph p-adjustment text-left">
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
            </p>
            <p className="paragraph p-adjustment text-left">
                Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
            </p>
            <p className="paragraph p-adjustment text-left">
                Personal Information: any information that identifies or can be used to identify you, directly or indirectly.
            </p>
            <ul>
                <li className="question-list">
                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Invoice Point, which is responsible for your information under this Privacy Policy.
                </li>
                <li className="question-list">
                    Country: where Invoice Point or the owners/founders of Invoice Point are based, in this case, is the Netherlands.
                </li>
                <li className="question-list">
                    Customer: refers to the company, organization or person that signs up to use the Invoice Point Service to manage the relationships with your consumers or service users.
                </li>
                <li className="question-list">
                    Device: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Invoice Point and use the services.
                </li>
                <li className="question-list">
                    IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                </li>
                <li className="question-list">
                    Personnel: refers to those individuals who are employed by Invoice Point or are under contract to perform a service on behalf of one of the parties.
                </li>
                <li className="question-list">
                    Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                </li>
                <li className="question-list">
                    Service: refers to the service provided by Invoice Point as described in the relative terms (if available) and on this platform.
                </li>
                <li className="question-list">
                    Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                </li>
                <li className="question-list">
                    Website: Invoice Point."’s" site, which can be accessed via this URL: <span><a href="https://www.invoicepoint.com">www.invoicepoint.com</a></span>
                </li>
            </ul>
        </div>
    )
}